### ISSUE TITLE
Theme overrides scrollPastEnd option

### ISSUE THREAD

**Issue by alabamagan** [mohirio/jupyterlab-horizon-theme#5] opened 2021-04-02 12:10 UTC
I wasn't able to scroll past the last cell when I activate the theme.

**Comment by sbarrios93** [comment] 2021-04-04 16:05
Same issue here, even though "scrollPastEnd" is set to true

**Comment by mohirio** [comment] 2021-04-11 16:58
Thank you for reporting the issue, it took me so time to figure out what was the cause, but I believe it's fixed with in a12ea7076eb590ab2b7aa7e1346679aaf2dcacea.

**Closed** 2021-04-13 03:53 UTC
